/*
 * Spektrafilm for Android — host test: Hanatos2025 RGB->spectrum upsampling.
 * Copyright (C) 2026 Spektrafilm Android contributors.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version. See <https://www.gnu.org/licenses/>.
 *
 * Port of spektrafilm (GPLv3) by Andrea Volpato — film modeling powered by
 * spektrafilm.
 *
 * Loads the Hanatos2025 spectra LUT (irradiance_xy_tc.npy) and the coeffs LUT
 * (hanatos_irradiance_xy_coeffs_250304.lut), runs the C++ RGB->spectrum
 * upsampling for a handful of fixed linear RGB inputs, and compares against the
 * Python oracle reference dumped to spectral_upsampling_ref.spkvec (generated by
 * gen_reference.py). Prints per-RGB max_abs and overall PASS/FAIL.
 *
 * Build (from repo root):
 *   g++ -std=c++17 \
 *     -I engine/spektra-core/src/main/cpp \
 *     -I tools/parity \
 *     engine/spektra-core/src/main/cpp/tests/test_spectral_upsampling.cpp \
 *     engine/spektra-core/src/main/cpp/io/npy_lut.cpp \
 *     engine/spektra-core/src/main/cpp/kernels/spectral_upsampling.cpp \
 *     -o /tmp/test_spectral_upsampling
 */
#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

#include "io/npy_lut.h"
#include "kernels/spectral_upsampling.h"
#include "model/spectral.h"
#include "spkvec_io.h"

namespace {

// Lockstep with RGBS in gen_reference.py.
const double kTestRgbs[][3] = {
    {0.5, 0.5, 0.5},
    {0.18, 0.18, 0.18},
    {0.9, 0.1, 0.1},
    {0.1, 0.8, 0.1},
    {0.1, 0.1, 0.9},
    {0.0, 0.0, 0.0},
};
constexpr int kNumRgbs = sizeof(kTestRgbs) / sizeof(kTestRgbs[0]);

constexpr double kTolerance = 1e-4;

// LUT + reference asset locations relative to this source file's directory.
const char* kSpectraLut =
    "../../../../../../../spektrafilm/src/spektrafilm/data/luts/"
    "spectral_upsampling/irradiance_xy_tc.npy";
const char* kCoeffsLut =
    "../../../../../../../spektrafilm/src/spektrafilm/data/luts/"
    "spectral_upsampling/hanatos_irradiance_xy_coeffs_250304.lut";

}  // namespace

int main(int argc, char** argv) {
    // Allow overriding asset paths on the command line:
    //   test <ref.spkvec> <spectra.npy> <coeffs.lut>
    std::string ref_path =
        (argc > 1) ? argv[1]
                   : std::string(SPK_TEST_DIR) + "/spectral_upsampling_ref.spkvec";
    std::string spectra_path = (argc > 2) ? argv[2] : kSpectraLut;
    std::string coeffs_path = (argc > 3) ? argv[3] : kCoeffsLut;

    spk::NdArray spectra_lut;
    spk::NdArray coeffs_lut;
    try {
        spectra_lut = spk::load_npy(spectra_path);
        coeffs_lut = spk::load_coeffs_lut(coeffs_path);
    } catch (const std::exception& e) {
        std::printf("FAIL: loading LUTs: %s\n", e.what());
        return 1;
    }

    std::printf("spectra LUT shape: %dx%dx%d\n", spectra_lut.shape[0],
                spectra_lut.shape[1], spectra_lut.shape[2]);
    std::printf("coeffs  LUT shape: %dx%dx%d\n", coeffs_lut.shape[0],
                coeffs_lut.shape[1], coeffs_lut.shape[2]);

    spkvec::Array ref;
    try {
        ref = spkvec::read(ref_path);
    } catch (const std::exception& e) {
        std::printf("FAIL: reading reference %s: %s\n", ref_path.c_str(), e.what());
        return 1;
    }
    if (ref.shape.size() != 2 || (int)ref.shape[0] != kNumRgbs ||
        (int)ref.shape[1] != spk::kSpectralSamples) {
        std::printf("FAIL: reference shape mismatch (got %ux%u)\n",
                    ref.shape.empty() ? 0 : ref.shape[0],
                    ref.shape.size() > 1 ? ref.shape[1] : 0);
        return 1;
    }

    double overall_max = 0.0;
    for (int r = 0; r < kNumRgbs; ++r) {
        double spec[spk::kSpectralSamples];
        spk::rgb_to_spectrum_hanatos2025(kTestRgbs[r], spectra_lut, spec);

        double row_max = 0.0;
        for (int i = 0; i < spk::kSpectralSamples; ++i) {
            double ref_v = ref.data[r * spk::kSpectralSamples + i];
            double d = std::fabs(spec[i] - ref_v);
            if (d > row_max) row_max = d;
        }
        if (row_max > overall_max) overall_max = row_max;
        std::printf("rgb(%.2f,%.2f,%.2f)  max_abs=%.3e  %s\n", kTestRgbs[r][0],
                    kTestRgbs[r][1], kTestRgbs[r][2], row_max,
                    row_max <= kTolerance ? "PASS" : "FAIL");
    }

    bool pass = overall_max <= kTolerance;
    std::printf("\noverall max_abs=%.3e  tolerance=%.1e  -> %s\n", overall_max,
                kTolerance, pass ? "PASS" : "FAIL");
    return pass ? 0 : 1;
}
