/*
 * SpectraFilm for Android — END-TO-END host parity test for the camera optical
 * diffusion filter run through the WHOLE scan_film pipeline.
 * Copyright (C) 2026 SpectraFilm Android contributors. GPLv3.
 * Port of spektrafilm (GPLv3) by Andrea Volpato — film modeling powered by spektrafilm.
 *
 * The diffusion_bpm golden (tests/test_diffusion.cpp) only exercises
 * apply_diffusion_filter_um in STAGE ISOLATION. This test turns the camera
 * optical diffusion filter ON inside the full pipeline (FilmingStage.expose) and
 * runs the entire scan_film route (expose -> develop -> scan) through one
 * spk_simulate() / spk_simulate_tap() call, comparing the result to the
 * scan_diffusion oracle golden generated by gen_goldens.py.
 *
 * The case mirrors scan_portra_spatial (spatial effects ON, i.e. the C API's
 * halation_active != 0) but ADDITIONALLY enables camera.diffusion_filter with a
 * NON-default strength (family=black_pro_mist, strength=0.8). The oracle's
 * digest_params zeroes camera.diffusion_filter.active when
 * deactivate_spatial_effects=True, so the filter only lives on the spatial
 * branch; this test keeps spatial on, exactly like the generator.
 *
 * It checks film_log_raw + film_density_cmy + final_rgb against the golden
 * bit-exact (max_abs <= 1e-4, rms <= 1e-5), and confirms that turning the
 * diffusion filter OFF (everything else equal) changes the output — proving the
 * filter is the sole driver of the change and is genuinely active end-to-end.
 *
 * Build (host) — full source set, run from the cpp root:
 *   g++ -std=c++17 -O2 -I <cpp_root> -I <tools/parity> \
 *     tests/test_diffusion_e2e.cpp spektra.cpp \
 *     model/*.cpp kernels/*.cpp io/*.cpp profiles/*.cpp \
 *     runtime/params.cpp runtime/print_digest.cpp runtime/stages/*.cpp \
 *     -o /tmp/test_diffusion_e2e
 * Run (golden dirs default to the repo-root /home/user/Spectrafilmandroid path;
 * argv[4] optionally overrides the goldens ROOT for a git worktree):
 *   /tmp/test_diffusion_e2e <asset_dir> <scan_diffusion_golden_dir> <input.f64> \
 *     [goldens_root]
 */
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

#include "spkvec_io.h"
#include "spektra.h"

namespace {

const char* kAssetDir = "/home/user/spektrafilm/src/spektrafilm/data";
const char* kDiffusionGoldenDir =
    "/home/user/Spectrafilmandroid/tools/parity/goldens/scan_diffusion";
const char* kInputF64 =
    "/home/user/Spectrafilmandroid/engine/spektra-core/src/main/cpp/tests/"
    "scan_portra_input_rgb.f64";

bool check(const char* label, const float* got, const std::vector<float>& gold) {
    double max_abs = 0.0, sse = 0.0;
    size_t argmax = 0;
    for (size_t i = 0; i < gold.size(); ++i) {
        double d = std::fabs(static_cast<double>(got[i]) -
                             static_cast<double>(gold[i]));
        if (d > max_abs) { max_abs = d; argmax = i; }
        sse += d * d;
    }
    double rms = std::sqrt(sse / static_cast<double>(gold.size()));
    const double tol_max_abs = 1e-4, tol_rms = 1e-5;
    bool pass = (max_abs <= tol_max_abs) && (rms <= tol_rms);
    std::printf("[%s] max_abs=%.6e (tol %.0e) rms=%.6e (tol %.0e) "
                "worst idx=%zu got=%.8f gold=%.8f -> %s\n",
                label, max_abs, tol_max_abs, rms, tol_rms, argmax,
                got[argmax], gold[argmax], pass ? "PASS" : "FAIL");
    return pass;
}

double max_abs_diff(const float* a, const float* b, size_t n) {
    double m = 0.0;
    for (size_t i = 0; i < n; ++i) {
        double d = std::fabs(static_cast<double>(a[i]) - static_cast<double>(b[i]));
        if (d > m) m = d;
    }
    return m;
}

// Build the scan_diffusion parameter set: scan_film route, spatial ON (the C API
// drives the spatial branch via halation_active != 0), camera optical diffusion
// ON with a NON-default strength. Grain/glare/stochastic off so it stays
// deterministic, matching gen_goldens.py's scan_diffusion case.
void set_diffusion_params(spk_params* p) {
    p->film_profile = "kodak_portra_400";
    p->print_profile = "kodak_portra_endura";
    spk_default_params(p);
    p->exposure_compensation_ev = 0.0f;
    p->auto_exposure = 0;
    p->density_curve_gamma = 1.0f;
    p->grain_active = 0;
    // Spatial branch ON (== oracle deactivate_spatial_effects=False): the C API
    // toggles in-emulsion scatter + halation + coupler diffusion + the camera
    // diffusion filter via halation_active.
    p->halation_active = 1;
    p->dir_couplers_active = 1;
    p->glare_active = 0;
    p->scan_film = 1;
    p->output_color_space = SPK_CS_SRGB;
    p->output_cctf_encoding = 1;
    p->rgb_to_raw_method = SPK_RGB2RAW_HANATOS2025;
    p->preview_max_size = 640;
    // Camera optical diffusion filter: ON, NON-default strength (schema default
    // is 0.5), black_pro_mist family, the rest at schema defaults.
    p->camera_diffusion_active = 1;
    p->camera_diffusion_strength = 0.8f;
    p->camera_diffusion_spatial_scale = 1.0f;
    p->camera_diffusion_halo_warmth = 0.0f;
    p->camera_diffusion_core_intensity = 1.0f;
    p->camera_diffusion_core_size = 1.0f;
    p->camera_diffusion_halo_intensity = 1.0f;
    p->camera_diffusion_halo_size = 1.0f;
    p->camera_diffusion_bloom_intensity = 1.0f;
    p->camera_diffusion_bloom_size = 1.0f;
}

}  // namespace

int main(int argc, char** argv) {
    std::string asset_dir = argc > 1 ? argv[1] : kAssetDir;
    std::string golden_dir = argc > 2 ? argv[2] : kDiffusionGoldenDir;
    std::string input_path = argc > 3 ? argv[3] : kInputF64;
    if (argc > 4) {
        std::string root = argv[4];
        golden_dir = root + "/scan_diffusion";
    }

    spk_engine* eng = nullptr;
    spk_status st = spk_engine_create(asset_dir.c_str(), &eng);
    if (st != SPK_OK) {
        std::fprintf(stderr, "engine create failed: %s\n", spk_status_str(st));
        return 2;
    }

    spkvec::Array gold_rgb = spkvec::read(golden_dir + "/final_rgb.spkvec");
    spkvec::Array gold_logr = spkvec::read(golden_dir + "/film_log_raw.spkvec");
    spkvec::Array gold_cmy = spkvec::read(golden_dir + "/film_density_cmy.spkvec");
    const int height = static_cast<int>(gold_rgb.shape[0]);
    const int width = static_cast<int>(gold_rgb.shape[1]);
    const int npix = width * height;
    std::printf("Image: %dx%dx3 (%d pixels)\n", width, height, npix);

    std::vector<double> rgb64(static_cast<size_t>(npix) * 3);
    {
        std::ifstream in(input_path, std::ios::binary);
        if (!in) { std::fprintf(stderr, "cannot open %s\n", input_path.c_str()); return 2; }
        in.read(reinterpret_cast<char*>(rgb64.data()),
                static_cast<std::streamsize>(rgb64.size() * sizeof(double)));
        if (in.gcount() != static_cast<std::streamsize>(rgb64.size() * sizeof(double))) {
            std::fprintf(stderr, "input size mismatch\n");
            return 2;
        }
    }
    std::vector<float> rgb32(rgb64.begin(), rgb64.end());
    spk_image in_img{rgb32.data(), width, height, SPK_CS_PROPHOTO};

    spk_params p{};
    set_diffusion_params(&p);

    bool pass_logr = false, pass_cmy = false, pass_rgb = false;

    spk_image tap_logr{};
    st = spk_simulate_tap(eng, &in_img, &p, "film_log_raw", &tap_logr);
    if (st != SPK_OK) {
        std::fprintf(stderr, "tap(film_log_raw) failed: %s\n", spk_status_str(st));
    } else {
        pass_logr = check("diffusion_e2e film_log_raw", tap_logr.data, gold_logr.data);
        spk_image_free(&tap_logr);
    }

    spk_image tap_cmy{};
    st = spk_simulate_tap(eng, &in_img, &p, "film_density_cmy", &tap_cmy);
    if (st != SPK_OK) {
        std::fprintf(stderr, "tap(film_density_cmy) failed: %s\n", spk_status_str(st));
    } else {
        pass_cmy = check("diffusion_e2e film_density_cmy", tap_cmy.data, gold_cmy.data);
        spk_image_free(&tap_cmy);
    }

    spk_image out{};
    st = spk_simulate(eng, &in_img, &p, &out);
    if (st != SPK_OK) {
        std::fprintf(stderr, "spk_simulate failed: %s\n", spk_status_str(st));
        spk_engine_destroy(eng);
        return 2;
    }
    pass_rgb = check("diffusion_e2e final_rgb", out.data, gold_rgb.data);

    // --- Sanity: diffusion OFF (everything else equal, spatial still ON)
    //     changes the output, proving the diffusion filter is genuinely active
    //     end-to-end and is the sole driver of the difference vs. the golden. ---
    spk_params p_off = p;
    p_off.camera_diffusion_active = 0;
    spk_image out_off{};
    double diff_delta = 0.0;
    bool diff_active = false;
    st = spk_simulate(eng, &in_img, &p_off, &out_off);
    if (st != SPK_OK) {
        std::fprintf(stderr, "spk_simulate(diffusion off) failed: %s\n",
                     spk_status_str(st));
    } else {
        diff_delta = max_abs_diff(out.data, out_off.data,
                                  static_cast<size_t>(npix) * 3);
        diff_active = diff_delta > 1e-4;
        std::printf("[diffusion on vs off] max_abs = %.6e (must be > 0: the optical "
                    "diffusion filter spreads highlight energy) -> %s\n",
                    diff_delta, diff_active ? "DIFFUSION ACTIVE" : "DIFFUSION INERT?!");
        spk_image_free(&out_off);
    }
    spk_image_free(&out);

    spk_engine_destroy(eng);
    bool all = pass_logr && pass_cmy && pass_rgb && diff_active;
    std::printf("%s\n", all ? "ALL PASS" : "FAIL");
    return all ? 0 : 1;
}
